### ISSUE TITLE
Documentation: Unclear the difference between predict and forecast

### ISSUE THREAD

**Issue by AicyDC** [regel/loudml#103]
Predict command: The predict command will return model predictions for a given time range, and a given model.
Forecast command: The forecast command will return a time series forecast for a given time range, and a given model. 

I don't understand the difference between these two?

Also I have been unable to use either to make predictions. When I use both the CLI and the chronograf interface to predict a day in the future, or press the play button, the resulting graph I can view does not go past the present.

This is an example of one of the models I am using:
`
{
    "offset": "30s",
    "features": {
        "io": [
            {
                "metric": "avg",
                "field": "usage_system",
                "name": "used",
                "default": 0,
                "measurement": "cpu",
                "anomaly_type": "high"
            }
        ]
    },
    "bucket_interval": "40s",
    "name": "high_bucket",
    "default_datasource": "influx",
    "interval": "20s",
    "max_evals": 5,
    "type": "donut",
    "span": 10,
    "forecast": 5,
    "seasonality": {
        "daytime": true,
        "weekday": true
    }
}
`

**Comment by regel** [comment]
Hi @AicyDC, ok, what version is currently installed? Can you please paste a full log including your CLI command and the console output?

Agreed we can improve the docs.

We've written two functions with distinct goals:
-  `predict` is mainly designed to test the `fit` between historical data and the model output, or to detect live anomalies
- `forecast` is designed to forecast future data and is following a specific approach in most DL techniques

**Comment by AicyDC** [comment]
Training CLI output:
```
root@919535c3b6bc:/# loudml train --from "now-18h" --to "now" high_bucket
INFO:root:connecting to influxdb on influxdb:8086, using database 'chronograf'
INFO:root:train(high_bucket) range=2019-03-05T16:37:20.000Z-2019-03-06T10:38:00.000Z train_size=0.670000 batch_size=256 epochs=100)
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 1621 time periods
INFO:hyperopt.tpe:tpe_transform took 0.001926 seconds
INFO:hyperopt.tpe:TPE using 0 trials
INFO:hyperopt.tpe:tpe_transform took 0.002852 seconds
INFO:hyperopt.tpe:TPE using 1/1 trials with best loss 11.363714
INFO:hyperopt.tpe:tpe_transform took 0.002176 seconds
INFO:hyperopt.tpe:TPE using 1/2 trials with best loss 11.363714
INFO:hyperopt.tpe:tpe_transform took 0.002942 seconds
INFO:hyperopt.tpe:TPE using 2/3 trials with best loss 11.363714
INFO:hyperopt.tpe:tpe_transform took 0.002163 seconds
INFO:hyperopt.tpe:TPE using 3/4 trials with best loss 9.021168
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.5.0', 'console_scripts', 'loudml')()
  File "/usr/lib/python3/dist-packages/loudml/cli.py", line 867, in main
    args.exec(args)
  File "/usr/lib/python3/dist-packages/loudml/cli.py", line 538, in exec
    windows=windows,
  File "/usr/lib/python3/dist-packages/loudml/donut.py", line 974, in train
    abnormal=abnormal,
  File "/usr/lib/python3/dist-packages/loudml/donut.py", line 736, in _train_on_dataset
    trials=trials,
  File "/usr/lib/loudml/vendor/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/lib/loudml/vendor/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/lib/loudml/vendor/hyperopt/fmin.py", line 322, in fmin
    return trials.argmin
  File "/usr/lib/loudml/vendor/hyperopt/base.py", line 590, in argmin
    best_trial = self.best_trial
  File "/usr/lib/loudml/vendor/hyperopt/base.py", line 584, in best_trial
    assert not np.any(np.isnan(losses))
AssertionError
```

Training log output:
```
INFO:root:job[93162bf9-5ca2-4f87-8290-c33f93a3f10a] starting, nice=0
INFO:root:predict(high_bucket) range=2019-03-06T10:36:40.000Z-2019-03-06T10:38:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2019-03-06T10:30:40.000Z-2019-03-06T10:38:00.000Z
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 11 time periods
INFO:root:generating prediction
INFO:root:job[93162bf9-5ca2-4f87-8290-c33f93a3f10a] predicted values for 2 time buckets
INFO:root:saving 'high_bucket' prediction to 'influx'
INFO:root:job[93162bf9-5ca2-4f87-8290-c33f93a3f10a] done
INFO:root:job[5bf18a2b-4b93-41fd-a75f-050dad6908b8] starting, nice=0
INFO:root:predict(used_mem1) range=2019-03-06T10:36:00.000Z-2019-03-06T10:38:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2019-03-06T10:27:00.000Z-2019-03-06T10:38:00.000Z
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 11 time periods
INFO:root:generating prediction
INFO:root:job[5bf18a2b-4b93-41fd-a75f-050dad6908b8] predicted values for 2 time buckets
WARNING:root:anomaly still in progress for model 'used_mem1' at 2019-03-06T10:36:00.000Z (score = 99.9)
INFO:root:saving 'used_mem1' prediction to 'influx'
INFO:root:job[5bf18a2b-4b93-41fd-a75f-050dad6908b8] done
INFO:root:job[67978f56-5f20-45cb-86aa-b3f2cb704f1c] starting, nice=0
INFO:root:predict(disk_used_percent) range=2019-03-06T10:37:00.000Z-2019-03-06T10:38:20.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2019-03-06T10:30:40.000Z-2019-03-06T10:38:20.000Z
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 23 time periods
INFO:root:generating prediction
INFO:root:job[67978f56-5f20-45cb-86aa-b3f2cb704f1c] predicted values for 4 time buckets
WARNING:root:anomaly still in progress for model 'disk_used_percent' at 2019-03-06T10:37:00.000Z (score = 100.0)
WARNING:root:anomaly still in progress for model 'disk_used_percent' at 2019-03-06T10:37:20.000Z (score = 100.0)
WARNING:root:anomaly still in progress for model 'disk_used_percent' at 2019-03-06T10:37:40.000Z (score = 100.0)
WARNING:root:anomaly still in progress for model 'disk_used_percent' at 2019-03-06T10:38:00.000Z (score = 100.0)
INFO:root:saving 'disk_used_percent' prediction to 'influx'
INFO:root:job[67978f56-5f20-45cb-86aa-b3f2cb704f1c] done
INFO:root:job[6d929cad-4917-48e6-a4c5-e382c3657f14] starting, nice=0
INFO:root:predict(high_bucket) range=2019-03-06T10:37:20.000Z-2019-03-06T10:38:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2019-03-06T10:31:20.000Z-2019-03-06T10:38:00.000Z
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 10 time periods
INFO:root:generating prediction
INFO:root:job[6d929cad-4917-48e6-a4c5-e382c3657f14] predicted values for 1 time buckets
INFO:root:saving 'high_bucket' prediction to 'influx'
INFO:root:job[6d929cad-4917-48e6-a4c5-e382c3657f14] done
INFO:root:job[74596cf6-f49c-45d1-af29-3cd3d590ad42] starting, nice=0
INFO:root:predict(high_bucket) range=2019-03-06T10:37:20.000Z-2019-03-06T10:38:40.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2019-03-06T10:31:20.000Z-2019-03-06T10:38:40.000Z
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 11 time periods
INFO:root:generating prediction
INFO:root:job[74596cf6-f49c-45d1-af29-3cd3d590ad42] predicted values for 2 time buckets
WARNING:root:detected anomaly for model 'high_bucket' at 2019-03-06T10:38:00.000Z (score = 100.0)
INFO:root:saving 'high_bucket' prediction to 'influx'
INFO:root:job[74596cf6-f49c-45d1-af29-3cd3d590ad42] done
```

Forecast CLI output:
```
root@919535c3b6bc:/# loudml forecast --from "now" --to "now+1d" high_bucket -s
INFO:root:forecast(high_bucket) range=2019-03-06T10:51:20.000Z-2019-03-07T10:52:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2019-03-06T10:45:20.000Z-2019-03-07T10:52:00.000Z
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-06T10:52:00Z
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-06T10:52:40Z
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-06T10:53:20Z
.
.
. Lots of the same with different times
.
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-07T10:50:00Z
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-07T10:50:40Z
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-07T10:51:20Z
INFO:root:found 2170 time periods
INFO:root:generating prediction
INFO:root:saving 'high_bucket' prediction to 'influx'
```

Nothing showed up in the docker logs of the loudml machine for forecasting.

**Comment by AicyDC** [comment]
Sorry I didn't tell you what version I have installed. I am using the community loudml docker image, which says it is version 1.5.0

**Comment by regel** [comment]
In the forecast logs, the `avg` value is undefined for many 40s buckets, and then replaced by zero given your feature definition. Is this something to investigate?

```
INFO:root:missing data: field 'usage_system', metric 'avg', bucket: 2019-03-07T10:50:40Z
```

If you query influx, eg `show measurements`, what do you see?

tip: the settings below are no longer needed with 1.5.0, and also you can increase your span value(10), so 400s, to a larger value. The `span` is the sliding window size, one rule of thumb is to calculate the span value to be in a 6h-24h range, but it will increase historical data set size required for training.
```
	"forecast": 5,
	"seasonality": {
		"daytime": true,
		"weekday": true
	}
```

**Comment by AicyDC** [comment]
The forecast logs are empty for buckets that are in the future, but I thought that should be the case since it the purpose is to predict the future for which I don't have data for yet? 

`show measurements` includes
```
name: measurements
name
----
cpu
disk
diskio
grok_asg_anomaly
kernel
loudml
mem
nyc_taxi
processes
swap
system
```
`show field keys` returns under cpu
name: cpu
```
fieldKey         fieldType
--------         ---------
usage_guest      float
usage_guest_nice float
usage_idle       float
usage_iowait     float
usage_irq        float
usage_nice       float
usage_softirq    float
usage_steal      float
usage_system     float
usage_user       float
```

**Comment by regel** [comment]
Having « predict » and « forecast »caused confusion. So « predict » was renamed to « eval » (evaluation) on the master branch. Documentation is updated. 

Evaluation is really meant to evaluate model performance and compare model output values to the actual values in the TSDB. Anomaly detection is also built in evaluation.
