### ISSUE TITLE
AssertionError when training

### ISSUE THREAD

**Issue by tommy-couzens** [regel/loudml#105]
This is my model:
```
---
offset: 0s # set to from 30s
features:
  io:
  - metric: avg
    field: usage_system
    name: used
    default: 0
    measurement: cpu
    anomaly_type: high
bucket_interval: 1m
name: diskio_reads
default_datasource: influx
interval: 1m
max_evals: 25 # increased a lot
type: donut
span: 50 # increased a lot
```

This is my output when training:

```
root@919535c3b6bc:/tmp# loudml train --from "now-1d" --to "now" diskio_reads
INFO:root:connecting to influxdb on influxdb:8086, using database 'chronograf'
INFO:root:train(diskio_reads) range=2019-03-13T12:19:00.000Z-2019-03-14T12:20:00.000Z train_size=0.670000 batch_size=256 epochs=100)
INFO:root:connecting to influxdb on influxdb:8086, using database 'telegraf'
INFO:root:found 1441 time periods
INFO:hyperopt.tpe:tpe_transform took 0.001963 seconds
INFO:hyperopt.tpe:TPE using 0 trials
INFO:hyperopt.tpe:tpe_transform took 0.002229 seconds
INFO:hyperopt.tpe:TPE using 1/1 trials with best loss 45.880120
INFO:hyperopt.tpe:tpe_transform took 0.002181 seconds
INFO:hyperopt.tpe:TPE using 2/2 trials with best loss 45.660960
INFO:hyperopt.tpe:tpe_transform took 0.002181 seconds
INFO:hyperopt.tpe:TPE using 3/3 trials with best loss 45.660960
INFO:hyperopt.tpe:tpe_transform took 0.002152 seconds
INFO:hyperopt.tpe:TPE using 4/4 trials with best loss 45.442393
INFO:hyperopt.tpe:tpe_transform took 0.002964 seconds
INFO:hyperopt.tpe:TPE using 5/5 trials with best loss 45.442393
INFO:hyperopt.tpe:tpe_transform took 0.002162 seconds
INFO:hyperopt.tpe:TPE using 5/6 trials with best loss 45.442393
INFO:hyperopt.tpe:tpe_transform took 0.002238 seconds
INFO:hyperopt.tpe:TPE using 6/7 trials with best loss 44.001617
INFO:hyperopt.tpe:tpe_transform took 0.002155 seconds
INFO:hyperopt.tpe:TPE using 7/8 trials with best loss 44.001617
INFO:hyperopt.tpe:tpe_transform took 0.002178 seconds
INFO:hyperopt.tpe:TPE using 8/9 trials with best loss 44.001617
INFO:hyperopt.tpe:tpe_transform took 0.002143 seconds
INFO:hyperopt.tpe:TPE using 9/10 trials with best loss 44.001617
INFO:hyperopt.tpe:tpe_transform took 0.002227 seconds
INFO:hyperopt.tpe:TPE using 10/11 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002201 seconds
INFO:hyperopt.tpe:TPE using 11/12 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002162 seconds
INFO:hyperopt.tpe:TPE using 12/13 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002192 seconds
INFO:hyperopt.tpe:TPE using 13/14 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002185 seconds
INFO:hyperopt.tpe:TPE using 14/15 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002181 seconds
INFO:hyperopt.tpe:TPE using 15/16 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002181 seconds
INFO:hyperopt.tpe:TPE using 15/17 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002178 seconds
INFO:hyperopt.tpe:TPE using 16/18 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002230 seconds
INFO:hyperopt.tpe:TPE using 17/19 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002136 seconds
INFO:hyperopt.tpe:TPE using 17/20 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002180 seconds
INFO:hyperopt.tpe:TPE using 18/21 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002157 seconds
INFO:hyperopt.tpe:TPE using 19/22 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002191 seconds
INFO:hyperopt.tpe:TPE using 20/23 trials with best loss 41.591958
INFO:hyperopt.tpe:tpe_transform took 0.002150 seconds
INFO:hyperopt.tpe:TPE using 20/24 trials with best loss 41.591958
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.5.0', 'console_scripts', 'loudml')()
  File "/usr/lib/python3/dist-packages/loudml/cli.py", line 867, in main
    args.exec(args)
  File "/usr/lib/python3/dist-packages/loudml/cli.py", line 538, in exec
    windows=windows,
  File "/usr/lib/python3/dist-packages/loudml/donut.py", line 974, in train
    abnormal=abnormal,
  File "/usr/lib/python3/dist-packages/loudml/donut.py", line 736, in _train_on_dataset
    trials=trials,
  File "/usr/lib/loudml/vendor/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/lib/loudml/vendor/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/lib/loudml/vendor/hyperopt/fmin.py", line 322, in fmin
    return trials.argmin
  File "/usr/lib/loudml/vendor/hyperopt/base.py", line 590, in argmin
    best_trial = self.best_trial
  File "/usr/lib/loudml/vendor/hyperopt/base.py", line 584, in best_trial
    assert not np.any(np.isnan(losses))
AssertionError
```

**Comment by nonostar** [comment]
+1
Same here for elastic  datasource,
changing just a little the training window might correct the issue (or crash it sooner)...
changing default value to something else than 0 if missing bucket should correct the issue but screw the training

**Comment by regel** [comment]
Missing data points are usually a bad thing for DNNs. The donut model avoids this caveat by using missing data point reconstruction. So using `default: 0` or `previous` is one way to work around this problem but it's not strictly required here.

Using a large span (50 or more) is fine, but you may end up with an empty evaluation data set. The training time window is split (2/3, 1/3) into training and evaluation data sets. With large spans your evaluation data set could be empty and cause the failures seen in the logs. The `master` version has better error handling and should warn with an error message if this happens.
