### ISSUE TITLE
Error On Build

### ISSUE THREAD

**Issue by toni-moreno** [regel/loudml#107]
hi @regel I'm trying to build from source ( current master version) , but there is some errors and seems to be a dependency from tensorflow failed, show I install first ? ( no info about this requierement in the README.md , what about the other compilation errors?

````
make -C loudml install
make[1]: Entering directory '/src/loudml/loudml'
./setup.py install
running install
running bdist_egg
running egg_info
creating loudml.egg-info
writing loudml.egg-info/PKG-INFO
writing top-level names to loudml.egg-info/top_level.txt
writing dependency_links to loudml.egg-info/dependency_links.txt
writing entry points to loudml.egg-info/entry_points.txt
writing requirements to loudml.egg-info/requires.txt
writing manifest file 'loudml.egg-info/SOURCES.txt'
reading manifest file 'loudml.egg-info/SOURCES.txt'
writing manifest file 'loudml.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/loudml
copying loudml/warp10.py -> build/lib/loudml
copying loudml/worker.py -> build/lib/loudml
copying loudml/__init__.py -> build/lib/loudml
copying loudml/faker.py -> build/lib/loudml
copying loudml/datasource.py -> build/lib/loudml
copying loudml/randevents.py -> build/lib/loudml
copying loudml/mongo.py -> build/lib/loudml
copying loudml/cli.py -> build/lib/loudml
copying loudml/annotations.py -> build/lib/loudml
copying loudml/misc.py -> build/lib/loudml
copying loudml/schemas.py -> build/lib/loudml
copying loudml/server.py -> build/lib/loudml
copying loudml/donut.py -> build/lib/loudml
copying loudml/elastic.py -> build/lib/loudml
copying loudml/dummystorage.py -> build/lib/loudml
copying loudml/filestorage.py -> build/lib/loudml
copying loudml/model.py -> build/lib/loudml
copying loudml/memdatasource.py -> build/lib/loudml
copying loudml/metrics.py -> build/lib/loudml
copying loudml/elastic_aws.py -> build/lib/loudml
copying loudml/config.py -> build/lib/loudml
copying loudml/api.py -> build/lib/loudml
copying loudml/storage.py -> build/lib/loudml
copying loudml/vendor.py -> build/lib/loudml
copying loudml/influx.py -> build/lib/loudml
copying loudml/errors.py -> build/lib/loudml
creating build/lib/rmn_common
copying rmn_common/data_import.py -> build/lib/rmn_common
copying rmn_common/__init__.py -> build/lib/rmn_common
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/warp10.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/worker.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/__init__.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/faker.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/datasource.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/randevents.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/mongo.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/cli.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/annotations.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/misc.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/schemas.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/server.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/donut.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/elastic.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/dummystorage.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/filestorage.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/model.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/memdatasource.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/metrics.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/elastic_aws.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/config.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/api.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/storage.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/vendor.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/influx.py -> build/bdist.linux-x86_64/egg/loudml
copying build/lib/loudml/errors.py -> build/bdist.linux-x86_64/egg/loudml
creating build/bdist.linux-x86_64/egg/rmn_common
copying build/lib/rmn_common/data_import.py -> build/bdist.linux-x86_64/egg/rmn_common
copying build/lib/rmn_common/__init__.py -> build/bdist.linux-x86_64/egg/rmn_common
byte-compiling build/bdist.linux-x86_64/egg/loudml/warp10.py to warp10.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/worker.py to worker.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/faker.py to faker.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/datasource.py to datasource.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/randevents.py to randevents.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/mongo.py to mongo.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/cli.py to cli.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/annotations.py to annotations.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/misc.py to misc.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/schemas.py to schemas.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/server.py to server.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/donut.py to donut.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/elastic.py to elastic.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/dummystorage.py to dummystorage.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/filestorage.py to filestorage.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/model.py to model.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/memdatasource.py to memdatasource.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/metrics.py to metrics.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/elastic_aws.py to elastic_aws.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/config.py to config.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/api.py to api.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/storage.py to storage.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/vendor.py to vendor.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/influx.py to influx.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/loudml/errors.py to errors.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/rmn_common/data_import.py to data_import.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/rmn_common/__init__.py to __init__.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying loudml.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/loudml-1.5.0.14.gaedc455-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing loudml-1.5.0.14.gaedc455-py3.5.egg
creating /usr/local/lib/python3.5/dist-packages/loudml-1.5.0.14.gaedc455-py3.5.egg
Extracting loudml-1.5.0.14.gaedc455-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding loudml 1.5.0.14.gaedc455 to easy-install.pth file
Installing loudml-faker script to /usr/local/bin
Installing loudml script to /usr/local/bin
Installing loudmld script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/loudml-1.5.0.14.gaedc455-py3.5.egg
Processing dependencies for loudml===1.5.0.14.gaedc455
Searching for voluptuous>=0.10.5
Reading https://pypi.python.org/simple/voluptuous/
Downloading https://files.pythonhosted.org/packages/6e/5e/4e721e30cf175f9e11a5acccf4cd74898c32cae93580308ecd4cf7d2a454/voluptuous-0.11.5.tar.gz#sha256=567a56286ef82a9d7ae0628c5842f65f516abcb496e74f3f59f1d7b28df314ef
Best match: voluptuous 0.11.5
Processing voluptuous-0.11.5.tar.gz
Writing /tmp/easy_install-xmws1s2k/voluptuous-0.11.5/setup.cfg
Running voluptuous-0.11.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xmws1s2k/voluptuous-0.11.5/egg-dist-tmp-zhxn5no0
/usr/lib/python3/dist-packages/setuptools/dist.py:342: UserWarning: The version specified ('1.5.0.14.gaedc455') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
zip_safe flag not set; analyzing archive contents...
Moving voluptuous-0.11.5-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding voluptuous 0.11.5 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/voluptuous-0.11.5-py3.5.egg
Searching for uuid
Reading https://pypi.python.org/simple/uuid/
Downloading https://files.pythonhosted.org/packages/ce/63/f42f5aa951ebf2c8dac81f77a8edcc1c218640a2a35a03b9ff2d4aa64c3d/uuid-1.30.tar.gz#sha256=1f87cc004ac5120466f36c5beae48b4c48cc411968eed0eaecd3da82aa96193f
Best match: uuid 1.30
Processing uuid-1.30.tar.gz
Writing /tmp/easy_install-ju77kd2w/uuid-1.30/setup.cfg
Running uuid-1.30/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ju77kd2w/uuid-1.30/egg-dist-tmp-pyjvpg02
  File "build/bdist.linux-x86_64/egg/uuid.py", line 138
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax

zip_safe flag not set; analyzing archive contents...
Moving uuid-1.30-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding uuid 1.30 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/uuid-1.30-py3.5.egg
Searching for tensorflow==1.3.0
Reading https://pypi.python.org/simple/tensorflow/
No local packages or working download links found for tensorflow==1.3.0
error: Could not find suitable distribution for Requirement.parse('tensorflow==1.3.0')
Makefile:7: recipe for target 'install' failed
make[1]: Leaving directory '/src/loudml/loudml'
Makefile:10: recipe for target 'install' failed
make[1]: *** [install] Error 1
make: *** [install] Error 2
````

**Comment by toni-moreno** [comment]
Hi @regel  ,I've finally compiled loudml after install tensorflow with this  command
```bash
  pip3 install schedule numpy scipy matplotlib ipython jupyter pandas sympy nose h5py tensorflow==1.3.0 
````
But now this exception  happens on execute 

````
loudml_1         | Traceback (most recent call last):
loudml_1         |   File "/usr/local/bin/loudmld", line 11, in <module>
loudml_1         |     load_entry_point('loudml===1.5.0.14.gaedc455', 'console_scripts', 'loudmld')()
loudml_1         |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
loudml_1         |     return get_distribution(dist).load_entry_point(group, name)
loudml_1         |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
loudml_1         |     return ep.load()
loudml_1         |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
loudml_1         |     return self.resolve()
loudml_1         |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
loudml_1         |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
loudml_1         |   File "/usr/local/lib/python3.5/dist-packages/loudml-1.5.0.14.gaedc455-py3.5.egg/loudml/server.py", line 19, in <module>
loudml_1         |     import uuid
loudml_1         |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
loudml_1         |   File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
loudml_1         |   File "<frozen importlib._bootstrap>", line 896, in _find_spec
loudml_1         |   File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
loudml_1         |   File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
loudml_1         |   File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
loudml_1         |   File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
loudml_1         |   File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
loudml_1         |   File "/usr/local/lib/python3.5/dist-packages/uuid-1.30-py3.5.egg/uuid.py", line 138
loudml_1         |     if not 0 <= time_low < 1<<32L:
loudml_1         |                                 ^
loudml_1         | SyntaxError: invalid syntax
````

It seems something related to uuid lib.. can you tell me what to do now please?

Lots of thanks!

**Comment by toni-moreno** [comment]
Hi @regel I've finally compiled ok with 

This requirements.txt

````
dictdiffer>=0.7.1
uuid
Jinja2==2.10
python-crontab==2.3.5
dateutils>=0.6.6
Flask>=0.12.1
Flask-restful>=0.3.5
gevent>=1.3.1
networkx==1.11
tensorflow==1.3.0
h5py>=2.7.0
hyperopt==0.1
numpy>=1.10.0
Pebble>=4.3.8
pycrypto>=2.6.1
PyYAML>=3.11
voluptuous>=0.10.5
schedule
requests
influxdb
````

but now when started is working fine but an error message appear.

````
loudml_1         | /usr/local/lib/python3.5/dist-packages/loudml-1.5.0.14.gaedc455-py3.5.egg/loudml/config.py:121: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
loudml_1         |   config_data = yaml.load(config_file)
loudml_1         | ERROR:root:detected development environment - incremental training disabled
````

What exactly means?

**Comment by toni-moreno** [comment]
Seems to be working now ...
