### ISSUE TITLE
TransportError(503, 'search_phase_execution_exception') while working with elasticsearch

### ISSUE THREAD

**Issue by HazelCindy** [regel/loudml#139]
my elasticsearch logs are: org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:305) [elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:91) [elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) [elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.search.aggregations.MultiBucketConsumerService$TooManyBucketsException: Trying to create too many buckets. Must be less than or equal to: [10$
        at org.elasticsearch.search.aggregations.MultiBucketConsumerService$MultiBucketConsumer.accept(MultiBucketConsumerService.java:110) ~[elasticsearch-7.3.1.jar:7.3.$
        at org.elasticsearch.search.aggregations.InternalAggregation$ReduceContext.consumeBucketsAndMaybeBreak(InternalAggregation.java:83) ~[elasticsearch-7.3.1.jar:7.3.$
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.addEmptyBuckets(InternalDateHistogram.java:407) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.doReduce(InternalDateHistogram.java:449) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:135) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:130) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:490) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:404) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.SearchPhaseController$1.reduce(SearchPhaseController.java:699) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:101) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44) ~[elasticsearch-7.3.1.jar:7.3.1]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86) ~[elasticsearch-7.3.1.jar:7.3.1]

**Comment by robcowart** [comment]
This is not an issue with LoudML, rather due to changes in Elasticsearch 7.x there are two modifications I highly recommend for any time-series use-cases...

```
indices.query.bool.max_clause_count: 8192
search.max_buckets: 100000
```

The latter attribute, `search.max_buckets`, is most specific to the issue you are seeing, but there is a good chance the other will be needed at some time as well.

**Comment by HazelCindy** [comment]
> This is not an issue with LoudML, rather due to changes in Elasticsearch 7.x there are two modifications I highly recommend for any time-series use-cases...
> 
> ```
> indices.query.bool.max_clause_count: 8192
> search.max_buckets: 100000
> ```
> 
> The latter attribute, `search.max_buckets`, is most specific to the issue you are seeing, but there is a good chance the other will be needed at some time as well.

this works thanks
