### ISSUE TITLE
Numpy Issue During Installation

### ISSUE THREAD

**Issue by muthianikev** [regel/loudml#141]
I end up encountering the following problem while trying to run any loudml command from the terminal. Using Ubuntu 18.04 where i have loudml installed

File "/usr/lib/loudml/vendor/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/usr/lib/loudml/vendor/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/lib/loudml/vendor/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.5.0', 'console_scripts', 'loudml')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/loudml/cli.py", line 16, in <module>
    import loudml.datasource
  File "/usr/lib/python3/dist-packages/loudml/datasource.py", line 22, in <module>
    from . import (
  File "/usr/lib/python3/dist-packages/loudml/misc.py", line 9, in <module>
    import numpy as np
  File "/usr/lib/loudml/vendor/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/loudml/vendor/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)

**Comment by regel** [comment]
This error message signals numpy installation error.

Numpy is packaged as a vendor dependency in `loudml-base`

Perhaps there is a conflict with previous numpy local install? Can you run `pip3 freeze` to list installed PIP packages?

**Comment by muthianikev** [comment]
The numpy version is 1.17.1
