### ISSUE TITLE
Errors starting latest-devel-gpu container

### ISSUE THREAD

**Issue by robcowart** [regel/loudml#147]
I am trying to start the `latest-devel-gpu` and am getting the following error:

```
~# docker run -ti -p 8077:8077 -v /etc/loudml-gpu/config.yml:/etc/loudml/config.yml:ro  -v /var/lib/loudml:/var/lib/loudml:rw loudml/loudml:latest-devel-gpu
Traceback (most recent call last):
  File "/usr/bin/loudmld", line 11, in <module>
    load_entry_point('loudml===1.6.0-446132b4', 'console_scripts', 'loudmld')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'loudml.server'
```

Thanks for any help.

**Comment by regel** [comment]
Thanks Rob. I’ll have a look and add this test to the CI config.

Are you using GKE with the NVIDIA gpus? What is your kubectl config?

**Comment by robcowart** [comment]
Not on K8s at the moment. I first started with `docker-compose`, and then just used the `docker` command with the arguments seen above.

`docker-compose.yml`:

```
version: '3'
services:
  loudml-gpu:
    image: loudml/loudml:latest-devel-gpu
    container_name: loudml-gpu
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8077:8077/tcp
    volumes:
      - /var/lib/loudml-gpu:/var/lib/loudml:rw
      - /etc/loudml/config.yml:/etc/loudml/config.yml:ro
```

`docker` command:

```
docker run -it -p 8077:8077 -v /etc/loudml-gpu/config.yml:/etc/loudml/config.yml:ro  -v /var/lib/loudml:/var/lib/loudml:rw loudml/loudml:latest-devel-gpu
```

Output of `nvidia-smi` as run from with a container using `docker run --gpus all nvidia/cuda:9.0-base nvidia-smi`:

```
Wed Oct  2 06:33:40 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    On   | 00000000:01:00.0 Off |                  N/A |
| 36%   27C    P8     9W / 175W |      0MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by regel** [comment]
Reproduced; ok so this is a namespace conflict. The loudml-python client should be in a loudml-python namespace to avoid the conflict. I will release a new version on PyPI.

test:

```
root@loudml:/# mv /usr/local/lib/python3.6/dist-packages/loudml /usr/local/lib/python3.6/dist-packages/loudml_python
root@loudml:/# 

root@loudml:/# loudmld
INFO:root:starting Loud ML server on 0.0.0.0:8077
^CKeyboardInterrupt
2019-10-06T08:56:22Z
INFO:root:stopping
```

**Comment by regel** [comment]
Solved in the latest image.

Verified using the following pod config on GKE, `imagePullPolicy: Always` is used to ensure the latest tag is pulled.

```
apiVersion: v1
kind: Pod
metadata:
  name: loudml
  labels:
    app.kubernetes.io/name: loudml
    app.kubernetes.io/version: "latest-devel"
spec:
  restartPolicy: Never
  containers:
  - name: loudml
    image: registry.hub.docker.com/loudml/loudml:latest-devel-gpu
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        cpu: 100m
        nvidia.com/gpu: "1"
```

**Comment by robcowart** [comment]
Just tested it quickly... looks good now. Thanks!
