### ISSUE TITLE
Can't Seem to Get Training Working - "error":"'aggregations'" 

### ISSUE THREAD

**Issue by AddChickpeas** [regel/loudml#157]
Hello, 

I keep running into issues when trying to model. I keep getting "error":"'aggregations'". 

The field I am trying to pull data from is a numeric field in elasticsearch (type: long). Any idea what the issue I'm running into is?  

```
{
"bucket_interval":"1m",
"default_datasource":"elastic-firewall",
"timestamp_field":"@timestamp",
"features":[
{
"default":0,
"metric":"avg",
"field":"client.bytes",
"name":"avg_bytes"
}
],
"interval":60,
"max_evals":10,
"name":"bytes-model",
"offset":30,
"span":5,
"max_threshold":90,
"min_threshold":50,
"type":"donut"
}
```
```
{
"error":"'aggregations'",
"id":"dd2876fc-d845-482c-a4fc-6bc5464d156d",
"model":"bytes-model",
"result":null,
"state":"failed",
"type":"training"
}
```

A couple more notes: 
1. I saw in another ticket some people were using "type":"timeseries". When I try to use this, I am told the type does not exist. Is this something I would need to load? 

2. Should I be able to run a count of a non-numeric field? Ideally, I'd like to do something like train on something like the count of "Deny" actions in the firewall log. It seems like filtering the data based on this may be possible, but can't verify if I can run it that way since I can't any sort of model working.

**Comment by Xavear** [comment]
Dear AddChickpeas,

I can only answer question 1 for you:
As of version 1.5.0 the timeseries type was removed. You can donut instead. (source: https://loudml.io/en/loudml/reference/current/release-notes-1.5.0.html)

With respect to question 2:
I think you cannot train based on a count but maybe you can transform your data into a form where you have a column called "Is_denied?" with possible values 0 and 1, and train based on that? But this is purely a guess.

With kind regards,
Thom

**Comment by AddChickpeas** [comment]
Hi Thom, 

Thanks for the response. That's the same route I was thinking of taking on it. Another method I had been playing with was using Fluentd to count how many denies, accepts, etc per 30 seconds and output them to their own index. 

Do you have any insight on why the example is failing? It's just a simple average calculation on a numeric field. 
Here's the full error trace. The model is in the original post. 
```
INFO:root:job[6a2bdfa7-7839-4aa2-8ca2-a0a384952fa7] starting, nice=5                                                                                                               
INFO:root:train(bytes-model) range=2019-10-23T17:30:00.000Z-2019-11-22T17:31:00.000Z train_size=0.670000 batch_size=64 epochs=100)                                                                                                                                                                                                                              
ERROR:root:'aggregations'                                                                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                                                        
INFO:root:job[3508ed04-2cc2-4e80-9687-e978d0f3a40d starting, nice=5
INFO:root:train(bytes-model) range=2019-10-23T18:38:00.000Z-2019-11-22T18:39:00.000Z train_size=0.670000 batch_size=64 epochs=100)
ERROR:root:'aggregations'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/loudml/worker.py", line 57, in run
    res = getattr(self, func_name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/loudml/worker.py", line 102, in train
    **kwargs
  File "/usr/lib/python3/dist-packages/loudml/donut.py", line 937, in train
    for i, (_, val, timeval) in enumerate(data):
  File "/usr/lib/python3/dist-packages/loudml/elastic.py", line 672, in get_times_data
    for bucket in es_res['aggregations']['histogram']['buckets']:
KeyError: 'aggregations'
10.0.6.99 - - [2019-11-22 18:38:26 "POST /models/bytes-model/_train?from=now-30d&to=now HTTP/1.1" 200 147 0.004710
ERROR:root:job[3508ed04-2cc2-4e80-9687-e978d0f3a40d failed: 'aggregations'
```

**Comment by regel** [comment]
Hi Josh,

You wrote:

```
"features":[
{
"default":0,
"metric":"avg",
"field":"client.bytes",
"name":"avg_bytes"
}
],
```

Average of bytes? Perhaps replacing `avg` by `count` is what you intended (point 2) for bytes-model.

I can improve error logging. The Elasticsearch query is probably returning an exception although it is not caught nor printed here.
