### ISSUE TITLE
Dot in measurement name cause regular expression issue when performing training

### ISSUE THREAD

**Issue by gilangcp** [regel/loudml#169]
Hi, 

I am working with LoudML latest-devel, When I tried to invoke the training HTTP API it resulted in the following message:

`ERROR:root:job[559dcf5d-6a27-4919-a26f-f2d8b23d2e73] failed: invalid field measurement: does not match regular expression`

Example of measurement in the bucket:
`project.JvmFreeMemory`

Any Idea on how to solve this? 

Thank you!

**Comment by regel** [comment]
Hi, can you please dump the Loud ML version number?

**Comment by gilangcp** [comment]
```
{
    "host_id": "bec3a813c0814d4d43e6d875117b4759",
    "tagline": "The Disruptive Machine Learning API",
    "version": "1.6.0-6c674260"
}
```

I put the measurement name on the bucket. If I put the measurement name into the model it self, other error occured:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/loudml/vendor/pebble/pool/process.py", line 389, in worker_process
    send_result(channel, Result(task.id, result))
  File "/usr/lib/loudml/vendor/pebble/common.py", line 183, in send_result
    pipe.send(data)
  File "/usr/lib/loudml/vendor/pebble/pool/channel.py", line 98, in unix_send
    return self.writer.send(obj)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object '_compile_scalar.<locals>.validate_value'
```

Thanks

**Comment by gilangcp** [comment]
I tried to use the new chronograf and upgrade the LoudML to the latest version, the issue still persists.

```
{
    "host_id": "bec3a813c0814d4d43e6d875117b4759",
    "tagline": "The Disruptive Machine Learning API",
    "version": "1.6.0-0c5288ff"
}
```
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
loudml/loudml       latest-devel        c4ff414668fd        4 days ago          1.32GB
loudml/chronograf   latest              358746164cda        2 weeks ago         48.4MB
```
![Annotation 2020-01-31 122919](https://user-images.githubusercontent.com/1003224/73536811-239b1200-4427-11ea-8e71-6943fc99667c.jpg)

Thank you!

**Comment by Nitesh-vaidyanath** [comment]
@regel Any update on this issue ?

**Comment by vsergeyev** [comment]
@Nitesh-vaidyanath looking into this

**Comment by Isaac-Foo** [comment]
@regel Hi, I've face similar issues, is there any updates yet? I'm using the latest docker-compose version in the github.
