### ISSUE TITLE
loudmld not listening on TCP port if /var/lib/loudml contains unexpected content

### ISSUE THREAD

**Issue by regel** [regel/loudml#17]
EL7, running loudml-1.2.4

I notice that loudmld is started, but is not listening on port 8077.

The root cause appears to be an exception at start time, due to a model file containing unexpected data. This exception could be reproduced in an upgrade/downgrade scenario.

**Comment by vnyb** [comment]
I can't reproduce this bug. What do you mean exactly by unexpected data? I've added an extra field but not exception is raised. Could you provide an example?

**Comment by regel** [comment]
Yes, the steps to reproduce:
 - install the fingerprint version from a local rpm build,
 - create and save a fingerprint model,
 - uninstall this release
 - install 1.2.4 version
 - restart loudmld
 -> loudmld no longer responding on port 8077

An exception appears in the console when running loudmld. The exception is apparently preventing loudmld from starting completely, as we do not get responses to curl requests.

# loudmld
/usr/lib64/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/loudml/schemas.py", line 46, in validate
  File "/usr/lib/python3.4/site-packages/voluptuous/schema_builder.py", line 221, in __call__
    return self._compiled([], data)
  File "/usr/lib/python3.4/site-packages/voluptuous/schema_builder.py", line 538, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib/python3.4/site-packages/voluptuous/schema_builder.py", line 370, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['features']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/loudmld", line 9, in <module>
    load_entry_point('loudml==1.2', 'console_scripts', 'loudmld')()
  File "/usr/lib/python3.4/site-packages/loudml/server.py", line 666, in main
  File "/usr/lib/python3.4/site-packages/loudml/server.py", line 604, in restart_predict_jobs
  File "/usr/lib/python3.4/site-packages/loudml/storage.py", line 50, in load_model
  File "/usr/lib/python3.4/site-packages/loudml/model.py", line 159, in load_model
  File "/usr/lib/python3.4/site-packages/loudml/fingerprints.py", line 76, in __init__
  File "/usr/lib/python3.4/site-packages/loudml/model.py", line 86, in __init__
  File "/usr/lib/python3.4/site-packages/loudml/model.py", line 103, in validate
  File "/usr/lib/python3.4/site-packages/loudml/schemas.py", line 48, in validate
loudml.errors.Invalid: invalid field features: required key not provided

**Comment by regel** [comment]
Bug fixed in release 1.4.0
