### ISSUE TITLE
Scheduled predictions terminate with errors

### ISSUE THREAD

**Issue by simplelife2010** [regel/loudml#173]
I started experimenting with the _start api call to get regular anomaly detections. In my setup I had 4 models running simultaneously. The scheduled jobs are visible via list-scheduled-jobs. After about 24h they stop producing output and I recieve the following error:
```
INFO:schedule:Running job Every 300.0 seconds do daemon_exec_scheduled_job('_eval(198-ch2-ae-mse)') (last run: 2020-01-04 19:09:25, next run: 2020-01-04 19:14:25)
INFO:root:job[843596e1-f06c-4860-8453-20daa5e76d4e] starting, nice=0
INFO:root:predict(198-ch2-ae-mse) range=2020-01-04T18:00:00.000Z-2020-01-04T19:00:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2020-01-03T19:00:00.000Z-2020-01-04T19:00:00.000Z
INFO:root:connecting to influxdb on aim-influxdb-master.aim-staging.svc.cluster.local:8086, using database 'business_data_escalator'
INFO:root:found 24 time periods
INFO:root:generating prediction
INFO:root:job[843596e1-f06c-4860-8453-20daa5e76d4e] predicted values for 1 time buckets
WARNING:root:detected anomaly for model '198-ch2-ae-mse' at 2020-01-04T18:00:00.000Z (score = 100.0)
INFO:root:connecting to influxdb on aim-influxdb-master.aim-staging.svc.cluster.local:8086, using database 'business_data_escalator'
INFO:root:job[843596e1-f06c-4860-8453-20daa5e76d4e] done. Took 0:00:00.605445
127.0.0.1 - - [2020-01-04 19:14:26] "POST /models/198-ch2-ae-mse/_eval?from=1578161366&to=1578161666&save_output_data=True&output_bucket=frame_wise&flag_abnormal_data=True HTTP/1.1" 200 541 0.606498
INFO:schedule:Running job Every 300.0 seconds do daemon_exec_scheduled_job('_eval(198-ch2-fm1)') (last run: 2020-01-04 19:09:26, next run: 2020-01-04 19:14:26)
INFO:root:job[5336c270-5e4d-4375-a928-02cfc0831082] starting, nice=0
INFO:root:predict(198-ch2-fm1) range=2020-01-04T18:00:00.000Z-2020-01-04T19:00:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2020-01-03T19:00:00.000Z-2020-01-04T19:00:00.000Z
INFO:root:connecting to influxdb on aim-influxdb-master.aim-staging.svc.cluster.local:8086, using database 'business_data_escalator'
INFO:root:found 24 time periods
INFO:root:generating prediction
INFO:root:job[5336c270-5e4d-4375-a928-02cfc0831082] predicted values for 1 time buckets
INFO:root:job[5336c270-5e4d-4375-a928-02cfc0831082] done. Took 0:00:00.602062
127.0.0.1 - - [2020-01-04 19:14:28] "POST /models/198-ch2-fm1/_eval?from=1578161367&to=1578161667&save_output_data=True&output_bucket=frame_wise&flag_abnormal_data=True HTTP/1.1" 200 447 0.603621
INFO:schedule:Running job Every 1 minute do daemon_clear_jobs() (last run: 2020-01-04 19:13:26, next run: 2020-01-04 19:14:26)
INFO:schedule:Running job Every 300.0 seconds do daemon_exec_scheduled_job('_eval(882-ch1-ae-mse)') (last run: 2020-01-04 19:09:57, next run: 2020-01-04 19:14:57)
INFO:root:job[891198ec-84c5-4171-bdaa-0657b1cc8d76] starting, nice=0
INFO:root:predict(882-ch1-ae-mse) range=2020-01-04T18:00:00.000Z-2020-01-04T19:00:00.000Z
INFO:root:setting threshold range min=68.000000 max=99.700000
INFO:root:extracting data for range=2020-01-03T19:00:00.000Z-2020-01-04T19:00:00.000Z
INFO:root:connecting to influxdb on aim-influxdb-master.aim-staging.svc.cluster.local:8086, using database 'business_data_escalator'
INFO:root:found 24 time periods
INFO:root:generating prediction
INFO:root:job[891198ec-84c5-4171-bdaa-0657b1cc8d76] predicted values for 1 time buckets
INFO:root:connecting to influxdb on aim-influxdb-master.aim-staging.svc.cluster.local:8086, using database 'business_data_escalator'
Exception in thread Thread-101531:
Traceback (most recent call last):
  File "/usr/lib/loudml/vendor/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/loudml/vendor/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/loudml/vendor/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/loudml/vendor/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/loudml/vendor/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/loudml/vendor/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/loudml/vendor/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/loudml/vendor/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/loudml/vendor/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8077): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/loudml/requests.py", line 30, in perform_request
    response = session.send(prepared_request, **send_kwargs)
  File "/usr/lib/loudml/vendor/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/loudml/vendor/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8077): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/loudml/server.py", line 234, in callback
    self.cb(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/loudml/server.py", line 416, in read_messages
    schedule.run_pending()
  File "/usr/lib/loudml/vendor/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib/loudml/vendor/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/lib/loudml/vendor/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/lib/loudml/vendor/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "/usr/lib/python3/dist-packages/loudml/server.py", line 178, in daemon_exec_scheduled_job
    headers=None,
  File "/usr/lib/python3/dist-packages/loudml/requests.py", line 35, in perform_request
    raise errors.ConnectionTimeout('TIMEOUT', str(e), e)
TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given

```

It seems to me that a scheduled job tries to call the _eval function via api and gets a timeout. After that, all scheduled jobs still exist, but stopped working.

Any help appreciated.
Bruno

**Comment by simplelife2010** [comment]
Could this be the problem?

The exception is raised here (perhaps due to a database connection problem, I don't know):
```requests.py```
```
...
    except Exception as e:
        if isinstance(e, requests.exceptions.SSLError):
            raise errors.SSLError('N/A', str(e), e)
        if isinstance(e, requests.Timeout):
            **raise errors.ConnectionTimeout('TIMEOUT', str(e), e)**
...
```
The signature does not conform to
```errors.py```
```
...
class LoudMLException(Exception):
    """Loud ML exception"""
    code = 500

    **def __init__(self, msg=None):**
        super().__init__(msg or self.__doc__)
...
```
This would explain the TypeError. And that one could perhaps stop the scheduled job from working.

**Comment by simplelife2010** [comment]
It actually explains the TypeError. I patched the code in ```requests.py``` to just provide an ```str(e)``` as parameter for ```errors.ConnectionTimeout```.

The problem is now, that the exception ```ConnectionTimeout``` is not catched inside ```server.py```. The result is, that all scheduled jobs stop working. Should there be a try-block around ```perform_request```? Then, if we run into a timeout, the current job is just ended and retried in the next period.

**Comment by regel** [comment]
Hi Bruno. Thanks for all the infos. I can reproduce it, and will push a quick fix today.

**Comment by simplelife2010** [comment]
I will test it.

I have seen that you have not changed any Exception signatures (see my comment above about ```requests.py``` and ```errors.py```. Is my assumption wrong that we will get a TypeError if ```ConnectionTimeout``` is called with four parameters (including ```self```), when ```__init__``` has only two?.

**Comment by regel** [comment]
I've done a quick fix that will work, but you're right: the root cause is missing parameters the __init__ call and the exception handling can be improved. I'm still working on these improvements and will add one extra commit to fix this. Thanks so much for the code review.

**Comment by simplelife2010** [comment]
I can confirm that the issue is solved.
