### ISSUE TITLE
Error while training model

### ISSUE THREAD

**Issue by gbour** [regel/loudml#19]
Hello,

Trying & testing loudml.
Unfortunately, I got following error when training my model:
```
$> loudml train  loudml-timeseries-model --from "now-3d" --to "now-2d"
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:train(loudml-timeseries-model) range=[2018-04-21T13:43:47.902Z, 2018-04-22T13:43:47.903Z] train_size=0.670000 batch_size=64 epochs=100)
INFO:root:connecting to influxdb on 127.0.0.1:8086, using database 'collectd'
INFO:root:found 289 time periods
INFO:root:Preprocessing. mins: [0.] maxs: [2.84758255e+08] ranges: [2.84758255e+08]
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.2', 'console_scripts', 'loudml')()
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 432, in main
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 257, in exec
  File "/usr/lib/python3.5/dist-packages/loudml/timeseries.py", line 543, in train
  File "/usr/lib/python3.5/dist-packages/loudml/timeseries.py", line 415, in _train_on_dataset
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python3.5/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable
```

loudml is installed on debian 9.4
```
$> python3 -V
Python 3.5.3

$> pip3 list
elasticsearch (6.2.0)
influxdb (5.0.0)
tensorflow (1.3.0)
hyperopt (0.1)
dateutils (0.6.6)

$> # dpkg -l loudml*
ii  loudml                                         1.2.4 
ii  loudml-influx                                  1.2.4   

$> cat model.yml 
---
name: loudml-timeseries-model
type: timeseries
default_datasource: monitor
# Size of buckets for data aggregation and prediction 
bucket_interval: 5m
# Number of preceding buckets required to predict the next bucket
span: 3
# interval in seconds
interval: 60
offset: 30
max_evals: 5
features:
  - name: calls
    measurement: kamailio_value
    metric: sum
    field: value
    default: 0
```

**Comment by regel** [comment]
Thank you Guillaume, can you please copy/paste pip3 freeze output? We have seen issues with 'networkx' package, let's have a look at the version installed.

**Comment by gbour** [comment]
here it is
```
# pip3 freeze
aniso8601==0.83
bleach==1.5.0
certifi==2018.4.16
chardet==3.0.4
click==6.6
colorama==0.3.7
dateutils==0.6.6
decorator==4.3.0
elasticsearch==6.2.0
Flask==0.12.1
Flask-RESTful==0.3.5
future==0.16.0
h5py==2.7.0
html5lib==0.9999999
hyperopt==0.1
idna==2.6
influxdb==5.0.0
iotop==0.6
itsdangerous==0.24
Jinja2==2.8
loudml==1.2
loudml-influx==1.2
Markdown==2.6.11
MarkupSafe==0.23
networkx==2.1
nose==1.3.7
numpy==1.14.2
protobuf==3.5.2.post1
psutil==5.0.1
pycurl==7.43.0
pygobject==3.22.0
pymongo==3.6.1
python-apt==1.4.0b3
python-dateutil==2.7.2
pytz==2018.4
PyYAML==3.12
requests==2.18.4
scipy==1.0.1
six==1.11.0
tensorflow==1.3.0
tensorflow-tensorboard==0.1.8
urllib3==1.22
voluptuous==0.9.3
Werkzeug==0.14.1
```

**Comment by gbour** [comment]
Thanks @regel, it does the trick ! :smiley:
