### ISSUE TITLE
Traceback on macOS - /etc/os-release file not present

### ISSUE THREAD

**Issue by vsergeyev** [regel/loudml#208]
Hello, running loudmld in dev environment on macOS 10.14 and got a traceback

    Traceback (most recent call last):
    File "/Users/vserh/Documents/Temp/loudml/loudml/loudml/server.py", line 107, in wrapper
        return job_func(*args, **kwargs)
    File "/Users/vserh/Documents/Temp/loudml/loudml/loudml/server.py", line 1878, in daemon_send_metrics
        send_metrics(g_config.metrics, g_storage, user_agent="loudmld")
    File "/Users/vserh/Documents/Temp/loudml/loudml/loudml/metrics.py", line 47, in send_metrics
    'distribution': os_release.get("os-release", "NAME"),
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 780, in get
        d = self._unify_values(section, vars)
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1146, in _unify_values
        raise NoSectionError(section) from None
    configparser.NoSectionError: No section: 'os-release'

Reason should be a fact, that there is no '/etc/os-release' file in macOS.

It is likely the way to get OS name is

    cat /System/Library/CoreServices/SystemVersion.plist

Regards,
-- Volodymyr

**Comment by vsergeyev** [comment]
Btw, I see another workaround from docs - setting in config.yml

    metrics:
      enable: false
