### ISSUE TITLE
Internal server error when activating a model in the middle of training

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#53]
The following error is produced when a model that is in the middle of training and I attempt to activate it:
```python
[2018-10-19 10:13:13,160] ERROR in app: Exception on /models/ml-test/_start [POST]
Traceback (most recent call last):
  File "/usr/lib/loudml/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/loudml/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/loudml/vendor/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/lib/loudml/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/loudml/vendor/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/loudml/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/loudml/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/dist-packages/loudml/server.py", line 788, in model_start
  File "/usr/lib/python3.5/dist-packages/loudml/timeseries.py", line 506, in set_run_state
AttributeError: 'NoneType' object has no attribute 'pop'
ERROR:flask.app:Exception on /models/ml-test/_start [POST]
Traceback (most recent call last):
  File "/usr/lib/loudml/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/loudml/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/loudml/vendor/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/lib/loudml/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/loudml/vendor/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/loudml/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/loudml/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/dist-packages/loudml/server.py", line 788, in model_start
  File "/usr/lib/python3.5/dist-packages/loudml/timeseries.py", line 506, in set_run_state
AttributeError: 'NoneType' object has no attribute 'pop'
```

I know this is an invalid use case, but it should give back a 4xx error.

**Comment by regel** [comment]
fixed in 1.4.3, will be released shortly

**Comment by daradermody** [comment]
Can confirm fixed in 1.4.3.
