### ISSUE TITLE
LoudML crash

### ISSUE THREAD

**Issue by Milan-Faizal** [regel/loudml#61]
Hi, I'm using docker-compose to run TICK stack and loudml. Every other service except loudml is starting successfully. The logs are given below:

loudml_1      | Traceback (most recent call last):
loudml_1      |   File "/usr/bin/loudmld", line 11, in <module>
loudml_1      |   load_entry_point('loudml==1.4', 'console_scripts', 'loudmld')()
loudml_1      |   File "/usr/lib/python3.5/dist-packages/loudml/server.py", line 999, in main
loudml_1      |   File "/usr/lib/python3.5/dist-packages/loudml/config.py", line 124, in load_config
loudml_1      |   File "/usr/lib/python3.5/dist-packages/loudml/config.py", line 50, in __init__
loudml_1      | TypeError: argument of type 'NoneType' is not iterable
default_loudml_1 exited with code 1

I'm assuming that docker is using python2 by default instead of python3. The files shown in the log (except "/usr/bin/loudmld" ) are not present in the host directory so I cannot check the files for errors. I'm new to docker and loudml so I don't know where to look for a solution.Why is loudml crashing?Is it because docker is using python2 by default?If so, How to change it?
PS: I'm not using any Dockerfile

OS : ubuntu 18.04

config.yml
---------------

```
---

datasources:
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: from_loudml

storage:
  path: /var/lib/loudml

server:
listen: 0.0.0.0:8077 


```

----------------------------------

docker-compose.yml
---------------------------
```
# This is a Docker Compose file to work with Loud ML and an InfluxDB stack.

version: "2"

services:
  loudml:
    image: loudml/community
    volumes:
      - ./etc/loudml/config.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf
    depends_on:
      - influxdb
      - loudml
      - kapacitor
    ports:
      - "8888:8888"
    volumes:
      - ./var/chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
      KAPACITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor:latest
    depends_on:
      - influxdb
    volumes:
      - ./var/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086

  telegraf:
    image: telegraf:latest
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    environment:
       INFLUXDB_URL: http://influxdb:8086

> ### ### **`----------------------------------------------------------```**
```

**Comment by Milan-Faizal** [comment]
`services:
  loudml:
    image: loudml/community
    volumes:
      - ./etc/loudml/config.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb`

I replaced "config.yml" with "loudml.yml" and its working fine
