### ISSUE TITLE
Exception thrown at the end of the forecast command

### ISSUE THREAD

**Issue by jorgelbg** [regel/loudml#79]
While trying to use the forecast command in the terminal (inside the Docker container) I get the following exception:

```
INFO:root:missing data: field 'value', metric 'max', bucket: 2018-11-22T14:30:00Z
INFO:root:missing data: field 'value-derive', metric 'mean', bucket: 2018-11-22T15:00:00Z
INFO:root:missing data: field 'value', metric 'max', bucket: 2018-11-22T15:00:00Z
INFO:root:found 52 time periods
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.4', 'console_scripts', 'loudml')()
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 611, in main
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 409, in exec
  File "/usr/lib/python3.5/dist-packages/loudml/timeseries.py", line 1405, in forecast
ValueError: could not broadcast input array from shape (2) into shape (1)
```

Executed command:

```
$ loudml forecast --from "now" --to "now+1d" avg_clickouts
```

LoudML version: `loudml/community:1.4.3`.

The `loudml predict` command succeeds without any issue.

**Comment by regel** [comment]
Hi Jorge, it's hard to tell at first glance. It is possible to attach your model.json settings file and a small data-set so we can reproduce and patch this issue quickly?

It's a multivariate model, is it?

**Comment by jorgelbg** [comment]
Hi @regel, yes it's a multivarate model. It has a couple of features. You can check the model.json [in this gist](https://gist.github.com/jorgelbg/c36c89b98f421e0870f27a0d5825bd21). Let me see if I can export some data for the sample dataset.

**Comment by regel** [comment]
Nice model;) thanks for the extra info, it will help

**Comment by regel** [comment]
Hi @jorgelbg, we rolled out significant changes into 1.5.0 which is now OSS. It's a significant departure from the previous version: no support for multivariate models at this time, and a new model type 'donut'.
