### ISSUE TITLE
ImportError: bad magic number in 'loudml'

### ISSUE THREAD

**Issue by opvizordz** [regel/loudml#9]
Any idea, why I get the following error using the latest 1.2.1 version:
 loudml create-model model.yml
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.2', 'console_scripts', 'loudml')()
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: bad magic number in 'loudml': b'\x17\r\r\n'

Thanks

**Comment by osunac** [comment]
The current package is limited to Debian Stretch only. Could it be that you are installing it on a Ubuntu system?

**Comment by opvizordz** [comment]
Yes, I tried Debian 8 and Ubuntu - my mistake. Debian 9 works fine. 
Thanks
